version: '3'
services:
  estatico-vote:
    image: nginx:alpine
    volumes:
      - ./vote-frontend:/usr/share/nginx/html
    ports:
      - 3000:80
    networks:
      - frontend
      - backend
      
  estatico-result:
    image: nginx:alpine
    volumes:
      - ./result-frontend:/usr/share/nginx/html
    ports:
      - 3001:80
    networks:
      - frontend
      - backend

  redis:
    image: redis:alpine
    networks:
      - frontend
      - backend
  
  db:
    image: postgres:11.10-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - backend
    ports:
      - '5432:5432'

  vote-backend:
    build: './vote-backend/'
    depends_on:
      - redis
      - db
    ports:
      - 3333:3333
    networks:
      - frontend

  result-backend:
    build: './result-backend/'
    ports:
      - 4444:4444
    depends_on:
      - redis
      - db
    networks:
      - backend
      - frontend

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-data:

networks:
  frontend:
  backend: