apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume-pv
spec:
  accessModes:
      - ReadWriteOnce
  capacity:
    storage: 1Gi
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
  storageClassName: my-data-disk
  claimRef:
    name: myvolume-pvc