name: Build result-backend (DEV)

on:
  push:
    branches:
      - "develop"
    paths:
      - 'result-backend/**'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: mycluster                    # NOME DO CLUSTER
  GKE_ZONE: southamerica-east1-a            # ZONA DO CLUSTER
  DEPLOYMENT_NAME: voteapp_backend          # NOME DO DEPLOYMENT
  IMAGE: voteapp_backend                    # IMAGEM DO POD

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Docker Login
      env: 
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Docker Build
      run: docker build ./result-backend -t ${{secrets.DOCKER_USER}}/result-backend:$GITHUB_SHA

    - name: Docker Publish
      run: docker push ${{secrets.DOCKER_USER}}/result-backend

    # # Configurando com a GCP
    # - uses: google-github-actions/setup-gcloud@master
    #   with:
    #     version: '290.0.1'
    #     service_account_key: ${{ secrets.GKE_SA_KEY }}
    #     project_id: ${{ secrets.GKE_PROJECT }}

    # # Configura o docker com as credenciais do gcloud
    # - run: |-
    #     gcloud --quiet auth configure-docker
    # # Busca as credenciais do GKE para poder fazer o deploy no cluster
    # - run: |-
    #     gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # # Builda uma imagem docker
    # - name: Build
    #   run: |-
    #     docker build \
    #       --tag "gabriel984/$IMAGE:$GITHUB_SHA" \
    #       --build-arg GITHUB_SHA="$GITHUB_SHA" \
    #       --build-arg GITHUB_REF="$GITHUB_REF" \
    #       result-backend/
    # # Da um push na imagem para o Google Container Registry
    # - name: Publish
    #   run: |-
    #     docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
    # # Set up kustomize
    # - name: Set up Kustomize
    #   run: |-
    #     curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
    #     chmod u+x ./kustomize
    # # Deploy the Docker image to the GKE cluster
    # - name: Deploy
    #   run: |-
    #     ./kustomize edit set image gcr.io/PROJECT_ID/IMAGE:TAG=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA
    #     ./kustomize build . | kubectl apply -f -
    #     kubectl rollout status deployment/$DEPLOYMENT_NAME
    #     kubectl get services -o wide