name: Build result-backend (DEV)

on:
  push:
    branches:
      - "develop"
    paths:
      - 'teste/**'
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: mycluster                    # NOME DO CLUSTER
  GKE_ZONE: southamerica-east1-a            # ZONA DO CLUSTER
  DEPLOYMENT_NAME: result-backend-deployment        # NOME DO DEPLOYMENT
  IMAGE: result-backend                   # IMAGEM DO POD

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    # Configurando com a GCP
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Busca as credenciais do GKE para poder fazer o deploy no cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    

    # Deploy the Docker image to the GKE cluster
    - name: Run Ls
      run: |-
        ls
        
    - name: Kubectl
      run: |-
        kubectl cp ./teste/index.html $(kubectl get pod -l app=nginx -o jsonpath="{.items[0].metadata.name}"):/usr/share/nginx/html -c nginx